### ISSUE TITLE
Clicking Create Email Campaign fails to log user in and take them to create a campaign page

### ISSUE THREAD

**Issue by randywsandberg** [Coded-Commerce-LLC/WP-Benchmark-Email#10]
**Setup:**
- WordPress 5.4.2
- Benchmark Email Lite 3.2
- Win Chrome 84.0.4147.105

**Steps to reproduce:**
1. **WIPE BROWSER'S CACHE**
2. **RESTART BROWSER**
3. Go to https://wpemailing.com/wp-admin/
4. Log in as admin
5. Click Posts > All Posts
6. For "Hello World!" post, click "Create Email Campaign"
--> note user is **NOT** logged in
7. Click "Click to use a new tab - if the below fails to authenticate properly." link
--> bug

**Expected:**
After clicking "Create Email Campaign", expected user to be logged into Benchmark Email and to land on iFramed create a campaign page. See Screenshot_00.png.

**Observed:**
Instead, after clicking "Create Email Campaign" user is taken to an iFramed page that presents a login screen (see Screenshot_01.png). Clicking the supplied "Click to use a new tab - if the below fails to authenticate properly." link takes user to a new page where once again they are presented with a login screen. See Screenshot_02.png.

**Reproducible?**
Always

**Workaround?**
Yes, if user first clicks on Benchmark > Interface they'll log into their Benchmark Email account. After which following the steps above will fail to reproduce this issue. This workaround worked on the following browsers:
- Win Chrome BETA 85.0.4183.48
- Win Firefox 79.0
- Win Edge 84.0.522.52
- Win IE 11.388.19041.0
- Win Opera 70.0.3728.95

**Occurs On:**
- Win Chrome 84.0.4147.105 **(workaround listed above failed)**
- Win Chrome BETA 85.0.4183.48
- Win Firefox 79.0
- Win Edge 84.0.522.52
- Win IE 11.388.19041.0
- Win Opera 70.0.3728.95

**Doesn't Occur On:**
Bug reproduces on all browsers tested.

**Screenshot_00.png**
![Screenshot_00](https://user-images.githubusercontent.com/19829655/89463027-27378a80-d723-11ea-9873-9e0cdfe0e4f8.png)

**Screenshot_01.png**
![Screenshot_01](https://user-images.githubusercontent.com/19829655/89463037-2c94d500-d723-11ea-9690-c7adbba28222.png)

**Screenshot_02.png**
![Screenshot_02](https://user-images.githubusercontent.com/19829655/89463045-2f8fc580-d723-11ea-9dca-b6e3db8cd67a.png)

**Comment by randywsandberg** [comment]
Reproducible using the above setup and steps with Safari browser on iPadOS 13.6.

**Comment by seanconklin** [comment]
I will write up a bug for Benchmark regarding their auth API call not properly encoding the URL within the returned redirect parameter. For the meantime and this release, I have removed the auth step only for Interface locations that contain a query string (the email create step only). Workaround. Seems to work provided the user has authenticated with the UI in recent days. Works as a band-aid.

**Comment by seanconklin** [comment]
Relates to commit #dd34a07c32d2852735fd4c360882766666835a68

**Comment by randywsandberg** [comment]
Using WordPress 5.4.2 + Benchmark Email Lite 3.2.4 + Win Chrome 84.0.4147.105. After clicking newly added "Open Benchmark Interface", a popup was displayed and user was logged in to Benchmark Email then redirected -- within the same popup screen -- to the send a campaign summary page (see screenshot).  Will investigate with other browsers before closing.

![Screenshot_01](https://user-images.githubusercontent.com/19829655/89718898-cc4aa100-d977-11ea-85eb-2a4d4bebf939.png)

**Comment by randywsandberg** [comment]
Also doesn't occur on:
Win Firefox 79.0
Win Edge 84.0.522.52
Win Opera 70.0.3728.95

Closing as cannot reproduce.
