### ISSUE TITLE
Open Benchmark Interface button on Benchmark Settings page produces popup window with blank contents

### ISSUE THREAD

**Issue by randywsandberg** [Coded-Commerce-LLC/WP-Benchmark-Email#11]
**Setup:**
- WordPress 5.4.2
- Benchmark Email Lite 3.2.4
- Win Firefox 79.0

**Steps to reproduce:**
1. **WIPE BROWSER'S CACHE**
2. **RESTART BROWSER**
3. Go to https://wpemailing.com/wp-admin/
4. Log in as admin
5. Click Snippets > All Snippets
6. Click > to Reset Benchmark Email plugin data
7. Click Benchmark > Settings
8. Enter proper Benchmark Username and Password
9. Click "Connect to Benchmark"
10. Click "Open Benchmark Interface"
--> bug

**Expected:**
Popup window to display Benchmark Email user's homepage. See Screenshot_00.png.

**Observed:**
Instead, popup window was a blank page (i.e., about:blank). See Screenshot_01.png.

**Reproducible?**
Always

**Occurs On:**
- Win Firefox 79.0
- Win Chrome 84.0.4147.105
- Win Edge 84.0.522.52
- Win Opera 70.0.3728.95

**Screenshot_00.png:**
![Screenshot_00](https://user-images.githubusercontent.com/19829655/89735263-17b38c80-da16-11ea-8d92-64cea316f4bb.png)

**Screenshot_01.png:**
![Screenshot_01](https://user-images.githubusercontent.com/19829655/89735271-29952f80-da16-11ea-950c-52e2e58e0ed9.png)

**Comment by seanconklin** [comment]
I believe I have this resolved. I reproduced it with Mac Firefox as well. The interface page was loading on top of the settings page. I've cleaned-up that code and separated them so it loads cleanly both unauthenticated or authenticated.

I'm not clear if there may be an additional problem with the pop-up and Window Firefox cleaned. Please re-test with this latest commit and see if that reproduces. I believe I fixed it by fixing the separation of these pages.

**Comment by randywsandberg** [comment]
Could not reproduce using WordPress 5.4.2 + **Benchmark Email Lite 3.2.4 (i.e., the latest dev version)** + Win Firefox 79.0. And by "could not reproduce", I mean the "Connect to Benchmark" has been removed from the Benchmark > Settings page both unauthenticated and authenticated (see attached screenshots). I am guessing this is the fix. That is, I am guessing the "Connect to Benchmark" button was never intended to be on the Benchmark > Settings. Is this correct?

**Unauthenticated:**
![Screenshot_01](https://user-images.githubusercontent.com/19829655/89840087-3f911600-db24-11ea-9b0f-70e04bd5ca5f.png)

**Authenticated:**
![Screenshot_02](https://user-images.githubusercontent.com/19829655/89840124-50da2280-db24-11ea-9d3a-d0dc8d70ba96.png)

**Comment by seanconklin** [comment]
You got it! Settings and Interface are separate pages, should be as clean and simple as possible.

**Comment by randywsandberg** [comment]
Closing as cannot reproduce.
