### ISSUE TITLE
Benchmark Email Settings: Enable debugging? enabled by default

### ISSUE THREAD

**Issue by randywsandberg** [Coded-Commerce-LLC/WP-Benchmark-Email#2]
Steps to reproduce:
1. Go to Benchmark > Settings
--> bug

Expected Enable debugging? to be disabled by default.

Instead, Enable debugging? was enabled by default:
![Screenshot_01](https://user-images.githubusercontent.com/19829655/60401541-ea6c8d80-9b37-11e9-9d96-56d0a9a20f2d.png)

Browser: Win Chrome version 75.0.3770.100 (Official Build) (64-bit)

Note that there might be a very good reason this feature is enabled by default. Especially with the plugin in alpha state. But, just wanted to bring this potential issue to the forefront.

**Comment by seanconklin** [comment]
It was off by default when I installed the plugin v3.0-alpha. I enabled it since this is a dev environment. I've installed the new v3.0-beta1 version and have cleared all settings from the DB so you can see it in a virgin state.

**Comment by randywsandberg** [comment]
Cannot reproduce issue using Benchmark Email Lite 3.2 and Win Chrome 84.0.4147.89. Closing as fixed.
![Screen_01](https://user-images.githubusercontent.com/19829655/87737401-bccca380-c78f-11ea-9497-a0c970111233.png)
