### ISSUE TITLE
Benchmark > Settings: Connect to Benchmark attempt failed to display error message

### ISSUE THREAD

**Issue by randywsandberg** [Coded-Commerce-LLC/WP-Benchmark-Email#3]
Steps to reproduce:
1. Install Benchmark Email Lite version 3.0-alpha
2. Activate plugin
3. Go to Benchmark > Settings
4. Click Connect to Benchmark
5. Enter username and click OK
6. For password, enter "WrongPassword" and click OK
--> bug

Expected an error message in a timely manner.

Instead, waited well over an hour and no error message was displayed. All that was displayed was each of the three fields stated, "Loading...".
![Screenshot_01](https://user-images.githubusercontent.com/19829655/60401643-8a76e680-9b39-11e9-8101-5daf104b561b.png)

Browser: Win Chrome version 75.0.3770.100 (Official Build) (64-bit)

**Comment by randywsandberg** [comment]
Issue reproducible if username is also wrong.

**Comment by randywsandberg** [comment]
Reproduced using WordPress 5.4.2 + Benchmark Email Lite 3.2 + Linux Chrome 84.0.4147.89.
![Screen_01](https://user-images.githubusercontent.com/19829655/87863835-bd427700-c914-11ea-8b7c-c532d17d17d5.png)

**Comment by seanconklin** [comment]
Fixed in v3.2.1 pending upcoming repository release as v3.3

**Comment by randywsandberg** [comment]
Could not reproduce using WordPress 5.4.2 + **Benchmark Email Lite 3.2.1** + Win Chrome 84.0.4147.89. Closing as fixed.

![Screenshot_01](https://user-images.githubusercontent.com/19829655/88448943-d3aa7000-cdf7-11ea-914b-291e9a4f17e9.png)
