### ISSUE TITLE
Benchmark > Interface: Two error messages displayed when not connected to Benchmark Email

### ISSUE THREAD

**Issue by randywsandberg** [Coded-Commerce-LLC/WP-Benchmark-Email#4]
**Setup:**
- XAMPP for Linux 7.4.8
- WordPress 5.4.2
- Benchmark Email Lite 3.2
- Linux Chrome 84.0.4147.89

**Steps to reproduce:**
1. Install Benchmark Email Lite version 3.2
2. Activate plugin
3. Go to Benchmark > Interface
--> bug

**Expected:**
No error messages on page.

**Observed:**
Two error messages at the top of the page:
- **Warning:** Cannot modify header information - headers already sent by (output started at /opt/lampp/htdocs/wordpress/wp-includes/script-loader.php:2209) in **/opt/lampp/htdocs/wordpress/wp-includes/pluggable.php** on line **1281**
- **Warning:** Cannot modify header information - headers already sent by (output started at /opt/lampp/htdocs/wordpress/wp-includes/script-loader.php:2209) in **/opt/lampp/htdocs/wordpress/wp-includes/pluggable.php** on line **1284**

See attached screenshot.

**Reproducible?**
Always using the setup above.

![Screenshot_01](https://user-images.githubusercontent.com/19829655/87867558-f85b9f00-c942-11ea-98d6-917df09687f8.png)

**Comment by randywsandberg** [comment]
Reproduced using XAMPP for Windows 7.4.8 + WordPress 5.4.2 + **Benchmark Email Lite 3.2.1** + Win Chrome 84.0.4147.89.

![Screenshot_01](https://user-images.githubusercontent.com/19829655/88458638-5527ef80-ce44-11ea-8b0a-1707e7ea16d8.png)

**Comment by randywsandberg** [comment]
Was NOT able to reproduce using:
- Ubuntu Desktop 20.04
- **Apache/2.4.41**
- **PHP 7.4.3**
- **MySQL 8.0.20-0ubuntu0.20.04.1**
- WordPress 5.4.2
- Benchmark Email Lite 3.2.1
- Win Chrome 84.0.4147.89

![Screenshot_01](https://user-images.githubusercontent.com/19829655/88465974-5ffe7680-ce7c-11ea-976b-02dd5e3ee518.png)

**Comment by seanconklin** [comment]
This one should be fixed now, related to the fix for #5. The redirection (the one that could not complete due to output having started) was removed in favor of a simpler menu.

**Comment by randywsandberg** [comment]
Could not reproduce using XAMPP for Windows 7.4.8 + WordPress 5.4.2 + Benchmark Email Lite 3.2.2 + Win Chrome 84.0.4147.89. 

![Screenshot_01](https://user-images.githubusercontent.com/19829655/88703618-c58f7480-d0c1-11ea-8ffd-be8901a80ac8.png)
Closing as fixed.
