### ISSUE TITLE
Benchmark > Interface: Page cannot be accessed when not connected to Benchmark Email

### ISSUE THREAD

**Issue by randywsandberg** [Coded-Commerce-LLC/WP-Benchmark-Email#5]
**Setup:**
- WordPress 5.4.2
- Benchmark Email Lite 3.2
- Linux Chrome 84.0.4147.89

**Steps to reproduce:**
1. Go to https://wpemailing.com/wp-admin/ and log in as an admin
2. Make sure Benchmark Email Lite is installed and activated but NOT connected to Benchmark Email
3. Go to Benchmark > Interface (i.e., https://wpemailing.com/wp-admin/admin.php?page=wpbme_interface)
--> bug

**Expected:**
User taken to https://wpemailing.com/wp-admin/admin.php?page=wpbme_interface page.

**Observed:**
User was taken to https://wpemailing.com/wp-admin/admin.php?page=wpbme_settings page.

**Reproducible?**
Always at wpemailing.com site.

**Notes:**
- Not reproducible using the above mentioned setup locally either using ServerPress (i.e., Desktop Server), XAMPP for Linux, or standard LAMP install on Ubuntu 20.04.
- Benchmark > Interface link can be seen at wpemailing.com. See attached screenshot.

![Screenshot_01](https://user-images.githubusercontent.com/19829655/87874718-ef89be00-c980-11ea-9c65-297bba0cb3a1.png)

**Comment by seanconklin** [comment]
This is intentional. We cannot show the interface when they are not connected with a UI token, so we redirect them to obtain it.

You likely weren't being redirected with ServerPress because you were getting some PHP debug notices that prevented the redirection header from operating, i.e. the notices popped-in before the redirection header and killed it. I'll look into anything that might be causing those notices, but those would be regarding other ticket(s).

So I believe this one is good to close.

**Comment by randywsandberg** [comment]
As noted above I was able to access the Interface page using ServerPress (i.e., Desktop Server), **XAMPP for Linux, and a standard LAMP install on Ubuntu 20.04.**

**Comment by seanconklin** [comment]
I believe this is a result of #4. I'll have a look at that one first.

**Comment by randywsandberg** [comment]
Hey Sean, I just setup a LAMP server on Linux sans any debug stuff. Thus, I was able to access the Benchmark > Interface page without an error message(s). See screenshot:

![Screenshot_01](https://user-images.githubusercontent.com/19829655/88464438-9386d400-ce6f-11ea-8a9e-32fec1a87876.png)

**Here are the players:**
- Ubuntu Desktop 20.04
- Apache/2.4.41
- PHP 7.4.3
- MySQL 8.0.20-0ubuntu0.20.04.1
- WordPress 5.4.2
- Benchmark Email Lite 3.2.1
- Win Chrome 84.0.4147.89

This means the ONLY site I have reproduced this bug (i.e., cannot access Benchmark > Interface page when NOT connected to Benchmark) is at https://wpemailing.com/wp-admin/.

**Comment by randywsandberg** [comment]
Could not reproduce using XAMPP for Windows 7.4.8 + WordPress 5.4.2 + **Benchmark Email Lite 3.2.2** + Win Chrome 84.0.4147.89. Meaning, Interface page is no longer accessible as designed. **LOVE IT!** Closing as fixed.

![Screenshot_01](https://user-images.githubusercontent.com/19829655/88471527-521e1500-cebf-11ea-8514-58c318e78713.png)
