### ISSUE TITLE
Benchmark > Settings: Get a FREE Benchmark Email account! link fails to open new browser window or tab

### ISSUE THREAD

**Issue by randywsandberg** [Coded-Commerce-LLC/WP-Benchmark-Email#6]
**Setup:**
- XAMPP for Linux 7.4.8
- WordPress 5.4.2
- Benchmark Email Lite 3.2
- Linux Chrome 84.0.4147.89

**Steps to reproduce:**
1. Install Benchmark Email Lite
2. Activate plugin
3. Go to Benchmark > Settings page
4. Click on Get a FREE Benchmark Email account! link

**Expected:**
Open the linked document in a new browser window or tab.

**Observed:**
User taken to https://www.benchmarkemail.com/?p=68907 in the original window.

**Reproducible?**
Always

**Notes:**
Not a bug. Just an enhancement request.

**Comment by seanconklin** [comment]
I addressed this in commit eda931c. Ready for testing!

**Comment by randywsandberg** [comment]
Could not reproduce using XAMPP for Windows 7.4.8 + WordPress 5.4.2 + **Benchmark Email Lite 3.2.1** + Win Chrome 84.0.4147.89. Closing as fixed.

![Screenshot_01](https://user-images.githubusercontent.com/19829655/88458555-c31fe700-ce43-11ea-83a5-fa3ca33d01d9.png)
