### ISSUE TITLE
Benchmark > Settings: Get a FREE Benchmark Email account! link fails to take user to SIGN UP FREE page

### ISSUE THREAD

**Issue by randywsandberg** [Coded-Commerce-LLC/WP-Benchmark-Email#7]
**Setup:**
- XAMPP for Linux 7.4.8
- WordPress 5.4.2
- Benchmark Email Lite 3.2
- Linux Chrome 84.0.4147.89

**Steps to reproduce:**
1. Install Benchmark Email Lite
2. Activate plugin
3. Go to Benchmark > Settings page
4. Click on Get a FREE Benchmark Email account! link
--> bug

**Expected:**
Take user to SIGN UP FREE page at https://ui.benchmarkemail.com/register. See Screenshot_01.png

![Screenshot_01](https://user-images.githubusercontent.com/19829655/87880086-ae56d580-c9a3-11ea-8d8a-9f2f35ed70e0.png)

**Observed:**
User taken to https://www.benchmarkemail.com/?p=68907 where they must click on **SIGN UP FREE** button on top of page to be taken to SIGN UP FREE page. See Screenshot_02.png.

![Screenshot_02](https://user-images.githubusercontent.com/19829655/87880097-b9aa0100-c9a3-11ea-92c4-bc7e2bd05504.png)

**Reproducible?**
Always

**Notes:**
We use the https://www.benchmarkemail.com/?p=68907 link on support docs as well. Thus, if we change the link above we also need to change it elsewhere.

**Comment by seanconklin** [comment]
Good point. Please check with Lisa and confirm that linking folks elsewhere works for our affiliate connection. I see in their settings panel https://ui.benchmarkemail.com/Partner/BannerAds that they only provide us this one link.

**Comment by randywsandberg** [comment]
Benchmark Email just confirmed the direct link https://ui.benchmarkemail.com/register?p=68907 does indeed give us partner credit.

**Comment by randywsandberg** [comment]
Could not reproduce using WordPress 5.4.2 + Benchmark Email Lite 3.2.4 + Win Chrome 84.0.4147.105. See screenshots. Closing as fixed.

![Screenshot_01](https://user-images.githubusercontent.com/19829655/89718739-3cf0be00-d976-11ea-9695-0f0d3592d2af.png)

![Screenshot_02](https://user-images.githubusercontent.com/19829655/89718747-4d089d80-d976-11ea-837e-e1418e633d16.png)
